### ISSUE TITLE
Finite State Machine nuXmv

### ISSUE THREAD

**Issue by evangelos-bitsikas** [SyNSec-den/hermes-spec-to-fsm#5]
When I run synthesizers to generate a finite state machine in ./smv-out.smv for nuXmv, is it possible that some transitions might be missing? Have you ever encountered this issue?

**Comment by ishtiaqniloy** [comment]
It may be possible because of a few factors:

- Inaccuracy of NEUTREX
- Missing or miscategorized keywords
- Insufficient DSL rules

Hope this helps.
